#!/bin/sh

SUDO=
if command -v sudo >/dev/null &&
    sudo -l | grep -q -e ' ALL$' -e xbps-remove; then
        SUDO=sudo
elif command -v doas >/dev/null && [ -f /etc/doas.conf ]; then
    SUDO=doas
elif [ "$(whoami)" != root ]; then
    SUDO='su root -c '\''"$@"'\'' -- -'
fi

$SUDO xbps-remove -Ro "$@"
