#!/bin/sh

SUDO=
if command -v sudo >/dev/null; then
    SUDO=sudo
elif command -v doas >/dev/null && [ -f /etc/doas.conf ]; then
    SUDO=doas
elif [ "$(whoami)" != root ]; then
    SUDO='su root -c '\''"$@"'\'' -- -'
fi

$SUDO xbps-remove -Ro "$@"
